[project]
name = "mem0-cathedral-mcp"
version = "2.0.0"
description = "Intelligent Mem0 MCP server with quality filtering and smart search"
requires-python = ">=3.10"
dependencies = [
    "mcp>=1.0.0",
    "mem0ai>=0.1.118",
]

[project.optional-dependencies]
dev = [
    "pytest>=7.0.0",
    "pytest-asyncio>=0.21.0",
]

[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"
